services:
  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    devices:
      - /dev/dri
      - /dev/kfd
#  shellgpt:
#    build: ./shell_gpt/build
#  #open-webui:
#      ports:
#          - 7860:8080
#      environment:
#          - OPENAI_API_KEY=foo
#          - OLLAMA_API_BASE_URL=http://ollama:11434
#      volumes:
#          - ./open-webui:/app/backend/data
#      container_name: open-webui
#      image: ghcr.io/open-webui/open-webui:main
#      restart: always
#      depends_on:
#        - ollama
